[package]
name = "needletail"
version = "0.3.0"
authors = ["Roderick Bovee <roderick@onecodex.com>"]
description = "FASTX parsing and k-mer methods"
keywords = ["FASTA", "FASTQ", "kmer", "bioinformatics"]
categories = ["science", "parsing"]
repository = "https://github.com/onecodex/needletail"
license = "MIT"
readme = "./README.md"
edition = "2018"

[features]
default = ["compression"]
compression = ["bzip2", "flate2", "xz2", "zip"]

[dependencies]
flate2 = { version="1.0.6", optional=true }
bzip2 = { version="0.3.3", optional=true }
xz2 = { version="0.1.6", optional=true }
zip = { version="0.5.0", optional=true }
memchr = "2.2.0"

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "benchmark"
harness = false
